### ISSUE TITLE
is this host only install?

### ISSUE THREAD

**Issue by spinmastercodes** [GoldenKittenPlays/FairAI#14]
im just wondering, id like to have this but not need everyone to download it

**Comment by GoldenKittenPlays** [comment]
> im just wondering, id like to have this but not need everyone to download it

Hmm I never tried to see if it would on only host only. I am not sure it will because of the config though. For some reason configs need to be synced between clients I think. I could be wrong though. I plan on further updating this but am running into a lot of issues in the update. Feel free to try and update me if it works or not.
